version: '3.8'

services:
  cache-system:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
  core-ledger-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: core_ledger
    restart: always